title: Sunjacket
email: hello@sunjacket.net
description: > # this means to ignore newlines until "baseurl:"
  Official website for Sunjacket, the four-piece band from Chicago.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sunjacket.net" # the base hostname & protocol for your site
twitter_username: sunjacket
github_username: sunjacket
host: 0.0.0.0

# Build settings
markdown: kramdown
